[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "market-ai"
version = "0.1.0"
description = "AI trading system"
readme = "README_FINAL.md"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["src*"]
