name: AI Trading Bot CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with ruff
        run: ruff . --select=E9,F63,F7,F82 --output-format=github

      - name: Lint with flake8
        run: flake8 . --select=E9,F63,F7,F82 --show-source --statistics

      - name: Check formatting with black
        run: >-
          black --check
          PRODUCTION/tools/no_trade_replay.py
          src/utils/config.py
          src/evaluation/risk_management.py
          tests/test_config.py

      - name: Type check with mypy
        run: mypy PRODUCTION/tools/no_trade_replay.py src/utils/config.py --ignore-missing-imports

      - name: Run tests
        run: pytest -q
        env:
          PYTHONPATH: .
          ALPACA_API_KEY: test_key_12345678
          ALPACA_SECRET_KEY: test_secret_12345678
          ALPACA_ENV: paper

      - name: Validate configuration
        run: python src/utils/config.py
        env:
          ALPACA_API_KEY: test_key_12345678
          ALPACA_SECRET_KEY: test_secret_12345678
          ALPACA_ENV: paper

      - name: No-trade replay
        run: python PRODUCTION/tools/no_trade_replay.py
